[build]
# Default target for the IDE; actual compilation overrides it via command-line.
target = "x86_64-linux-android"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
profile-rustflags = true
